Mention how to get realpath in pre-commit message

diff --git a/tools/team-props/git-hooks/pre-commit b/tools/team-props/git-hooks/pre-commit
--- a/tools/team-props/git-hooks/pre-commit
+++ b/tools/team-props/git-hooks/pre-commit
@@ -15,7 +15,7 @@ fi
 
 # This block allows for chaining pre-commit hooks if this hook is a global hook (via core.hooksPath) and there also exists a repo-specific pre-commit hook
 if [[ -f ".git/hooks/pre-commit" ]]; then
-  type realpath >/dev/null 2>&1 || { echo >&2 "NOTE: the realpath binary is required to chain to the repo-specific pre-commit hook. Ignoring."; exit 0; }
+  type realpath >/dev/null 2>&1 || { echo >&2 "NOTE: the realpath binary is required to chain to the repo-specific pre-commit hook.\nOn macOS, you can install it via \"brew install coreutils\".\nIgnoring."; exit 0; }
   if [[ "$(realpath "${BASH_SOURCE[0]}")" != "$(realpath ".git/hooks/pre-commit")" ]]; then
     .git/hooks/pre-commit
     exit $?
