Run ktlint as part of the pre-commit checks

diff --git a/tools/team-props/git-hooks/pre-commit b/tools/team-props/git-hooks/pre-commit
--- a/tools/team-props/git-hooks/pre-commit
+++ b/tools/team-props/git-hooks/pre-commit
@@ -1,4 +1,9 @@
 #!/bin/bash
+
+# With this, if a command returns an exit code that's not 0, the script will
+# fail
+set -e
+
 # Stops accidental commits to master and develop. Pulled from: https://gist.github.com/stefansundin/9059706
 # Install:
 # cd path/to/git/repo
@@ -12,6 +17,9 @@ if [[ "$BRANCH" == "master" || "$BRANCH" == "develop" ]]; then
   echo "If so, commit with -n to bypass this pre-commit hook."
   exit 1
 fi
+
+# Runs ktlint to make sure everything matches the desired style
+./gradlew ktlint
 
 # This block allows for chaining pre-commit hooks if this hook is a global hook
 # (via core.hooksPath) and there also exists a repo-specific pre-commit hook
